blank_issues_enabled: false
contact_links:
  - name: View documentation ğŸ“š
    url:
    about: Check out the official docs for answers to common questions.
  - name: Feature requests ğŸ’¡
    url:
    about: Suggest a new React hook idea.
  - name: Questions ğŸ’­
    url:
    about: Need support with a React hook problem? Open up a help request.
  - name: Donate â¤ï¸
    url:
    about: Love usehooks-ts? Show your support by donating today!
